package constants

var NETWORK_ID_TO_NFTPORT_CHAIN_MAPPING = map[string]string{
	POLYGON_DQL_ID: "polygon",
}

var POLYGON_NFTPORT_UID = NFTPORTQUEUE + POLYGON_DQL_ID
var POLYGON_CROSSMINT_UID = CROSSMINTQUEUE + POLYGON_DQL_ID

var NETWORK_ID_TO_CROSSMINT_CHAIN_MAPPING = map[string]string{
	POLYGON_DQL_ID: "poly",
}

const (
	NFTPORTVENDOR   = "NFTPORT"
	CROSSMINTVENDOR = "CROSSMINT"
)

var COLLECTION_VENDOR_MAPPING = map[string]string{
	NFTPORTVENDOR:   NFTPORTQUEUE,
	CROSSMINTVENDOR: CROSSMINTQUEUE,
}
