BEGIN;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS Accounts (
  Account_ID INT PRIMARY KEY AUTO_INCREMENT,
  Document_Number VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS OperationTypes (
  OperationType_ID INT PRIMARY KEY AUTO_INCREMENT,
  Description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Transactions (
  Transaction_ID INT PRIMARY KEY AUTO_INCREMENT,
  Account_ID INT NOT NULL,
  OperationType_ID INT NOT NULL,
  Amount DECIMAL(10,2) NOT NULL,
  EventDate DATETIME NOT NULL,
  FOREIGN KEY (Account_ID) REFERENCES Accounts(Account_ID),
  FOREIGN KEY (OperationType_ID) REFERENCES OperationTypes(OperationType_ID)
);
COMMIT;